[package]
name = "upp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = { version = "0.29.11", features = ["rwh_04"], default-features = false}
gl = "0.6.0"
raw-gl-context = "0.1.2"
